POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
	"firstName": "rishav",
	"lastName": "raj",
	"userName": "rissshavmngo",
	"email": "rishavi@gmail.com",
	"password": "abc"
}

###

POST  http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "utkarsh@gmail.com",
	"password": "123"
}


####
POST  http://localhost:5000/api/auth/userInfo HTTP/1.1
Content-Type: application/json

{
	"id": 1
}

####
POST http://localhost:5000/api/post/ HTTP/1.1
Content-Type: application/json

{
	"authorId" : 2,
	"title" : "My title",
	"content" : "My content"
}

####
GET http://localhost:5000/api/post/feed/null HTTP/1.1
Content-Type: application/json


####
POST http://localhost:5000/api/profile/3 HTTP/1.1
Content-Type: application/json

{
	"username":"rishavinmngo"
}

####
POST http://localhost:5000/api/post/2 HTTP/1.1
Content-Type: application/json


####
POST http://localhost:5000/api/profile/follow/8/4 HTTP/1.1
Content-Type: application/json

{
	"username":"rishavinmngo"
}

####
POST http://localhost:5000/api/profile/followers_list/5 HTTP/1.1
Content-Type: application/json

{
	"username":"rytnix"
}
###

POST  http://localhost:5000/api/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1ayIsImlhdCI6MTY0NjMxODk0NH0.CiZcF2cVwzoSCXEPem1pYLnjO8bJiblL9ouWaIRh2jE


###

GET http://localhost:5000/api/comment/1 HTTP/1.1
Content-Type: application/json 


###

GET http://localhost:5000/api/comment/reply/1 HTTP/1.1
Content-Type: application/json 

###
POST http://localhost:5000/api/comment/ HTTP/1.1
Content-Type: application/json

{
	"userId": 1,
	"postId": 3,
	"comment": "from google"
}


###

POST http://localhost:5000/api/search/ HTTP/1.1
Content-Type: application/json

{
	"search_query": "rishav utkars"
}